setwd("C://Users/JennGanda/Documents/R/R-training/assignment")
getwd()
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
head(outcome)
ncol(outcome)
nrows(outcome)
names(outcome)
str(outcome)
summary(outcome)